<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.weasis.thirdparty.org.jogamp</groupId>
    <artifactId>jogamp-native</artifactId>
    <version>${revision}${changelist}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>jogamp-macosx-aarch64</artifactId>
  <version>${sha1}</version>
  <packaging>jar</packaging>
  <name>JOGL - MacOSX aarch64</name>

  <properties>
    <native.configuration>natives/macosx-universal/libgluegen_rt.dylib; natives/macosx-universal/libjocl.dylib; natives/macosx-universal/libnativewindow_awt.dylib; natives/macosx-universal/libnativewindow_macosx.dylib; natives/macosx-universal/libnewt_head.dylib; natives/macosx-universal/libjogl_mobile.dylib; natives/macosx-universal/libjogl_desktop.dylib; processor=aarch64; osname=MacOSX</native.configuration>
    <jogamp.native.classifier>natives-macosx-universal</jogamp.native.classifier>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack-jogamp-natives</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.jogamp.gluegen</groupId>
                  <artifactId>gluegen-rt</artifactId>
                  <version>${jogamp.version}</version>
                  <classifier>${jogamp.native.classifier}</classifier>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>org.jogamp.jogl</groupId>
                  <artifactId>jogl-all</artifactId>
                  <version>${jogamp.version}</version>
                  <classifier>${jogamp.native.classifier}</classifier>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>org.jogamp.jocl</groupId>
                  <artifactId>jocl</artifactId>
                  <version>${jogamp.version}</version>
                  <classifier>${jogamp.native.classifier}</classifier>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
Bundle-SymbolicName: jogamp-macosx-aarch64
Bundle-Name: JOGL - MacOSX aarch64
Bundle-Version: ${jogamp.version}
Bundle-NativeCode: ${native.configuration}
Import-Package:
Fragment-Host: jogamp;bundle-version="${jogamp.version}"
Export-Package: !*
]]></bnd>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
