app.version=${project.version}
felix.framework.version=${felix.framework.version}
felix.gogo.version=${felix.gogo.version}
felix.gogo.shell.version=${felix.gogo.shell.version}
felix.gogo.command.version=${felix.gogo.command.version}
felix.bundlerepository.version=${felix.bundlerepository.version}
felix.configadmin.version=${felix.configadmin.version}
felix.prefs.version=${felix.prefs.version}
felix.scr.version=${felix.scr.version}
osgi.promise.version=${osgi.promise.version}
osgi.component.version=${osgi.component.version}
miglayout.version=${miglayout.version}
jaxb.osgi.version=${jaxb.osgi.version}
dockingframes.version=${dockingframes.version}
weasis.core.img.version=${weasis.core.img.version}
zip4j.version=${zip4j.version}
joml.version=${joml.version}
jackson.version=${jackson.version}
jackson.annotations.version=${jackson.annotations.version}
weasis.opencv.pkg.version=${weasis.opencv.pkg.version}
jogamp.version=${jogamp.version}
base.minimal.version=${base.minimal.version}
