<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.weasis.opencv</groupId>
    <artifactId>weasis-opencv</artifactId>
    <version>${revision}${changelist}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>weasis-opencv-core-linux-x86-64</artifactId>
  <version>${sha1}</version>
  <packaging>jar</packaging>
  <name>Weasis OpenCV native linux-x86-64</name>
  <description>Fragment attached to weasis-core-img. Install name weasis-opencv-core-linux-x86-64-${weasis.opencv.pkg.version}.jar</description>

  <properties>
    <sha1>${weasis.opencv.pkg.version}</sha1>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.weasis.thirdparty.org.opencv</groupId>
      <artifactId>libopencv_java</artifactId>
      <version>${weasis.opencv.native.version}</version>
      <type>so</type>
      <classifier>linux-x86-64-dyn</classifier>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-opencv-native</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.weasis.thirdparty.org.opencv</groupId>
                  <artifactId>libopencv_java</artifactId>
                  <version>${weasis.opencv.native.version}</version>
                  <type>so</type>
                  <classifier>linux-x86-64-dyn</classifier>
                  <overWrite>true</overWrite>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>libopencv_java.so</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
Bundle-SymbolicName: weasis-opencv-core-linux-x86-64
Bundle-Name: Weasis OpenCV native linux-x86-64
Bundle-Version: ${weasis.opencv.pkg.version}
Fragment-Host: weasis-core-img;bundle-version="${weasis.core.img.version}"
Bundle-NativeCode: libopencv_java.so; processor=x86-64; osname=Linux
Private-Package: org.weasis.opencv.internal
Export-Package: !*
Import-Package: *
]]></bnd>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>@{argLine} -Djava.library.path=${project.build.outputDirectory} -Dweasis.opencv.pkg.version=${weasis.opencv.pkg.version}</argLine>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
